# outer.yml
name: Outer Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pass-git-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
