name: Вручную запускаемый воркфлоу

on:
  workflow_dispatch:
    inputs:
      flag1:
        description: 'Флажок 1'
        required: false
        default: 'false'
      flag2:
        description: 'Флажок 2'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Шаг 1
        run: echo "Шаг 1"

      - name: Шаг 2
        run: echo "Шаг 2"

      - name: Шаг 3
        run: echo "Шаг 3"
